rails_recipes/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :events do
    # ***** 16-2 建立報名、16-3 多步驟表單(wizards) *****
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1        
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2       
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end
  
  resource :user  # 這個單數的用意是指唯一自己，登入作戶也不能修改其他人的資。

  namespace :admin do     #定義了一個命名空間,並在其中定義了其他資源。    
    resources :events do
      resources :registrations, :controller => "event_registrations"  
      resources :tickets, :controller => :event_tickets
      collection do
        post :bulk_update
      end 
      
      member do
        post :reorder
      end

    end

    resources :categories
    resources :users do
      resource :profile, :controller => :user_profiles
    end
    
    root "events#index"   #访问 "/admin" 路径时，会执行 "events#index" 动作。
  end

  
  get "/jquery-1" => "pages#jquery_1"
  get "/jquery-2" => "pages#jquery_2"
  get "/jquery-3" => "pages#jquery_3"
  get "/jquery-4" => "pages#jquery_4"
  get "/jquery-5" => "pages#jquery_5"
  get "/card-tab" => "pages#card_tab"
  
  root "events#index"

end

rails_recipes/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= #stylesheet_link_tag "application", "data-turbo-track": "reload" 
    %>
    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= #javascript_include_tag "application" 
    %>
    <%= javascript_include_tag 'admin' %>

  </head>

  <body>
    <div class="container-fluid"> <!-- "mx-5" 對 "container-fluid" 沒作用-->
      <!-- "navbar-expand-lg" 当屏幕尺寸达到 lg（大于等于 992 像素）时，导航栏将橫向扩展为全屏幕。-->
      <!-- <nav class="navbar navbar-default"> bs5中,"navbar-default"已被.navbar-light和.navbar-dark類別取代-->
      <!-- <nav class="navbar navbar-inverse navbar-fixed-top"> "navbar-inverse","navbar-fixed-top"在bs5中已刪除 -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top mx-3">     
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">全栈营 Rails Recipes 後台</a>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
            <% if current_user %>              
              <% if current_user.is_editor? %>
                <li class="active"> <%= link_to '活動管理', admin_events_path, :class => "nav-link" %> </li>
              <% end %>              
              <% if current_user.is_admin? %>
                <li> <%= link_to '用戶管理', admin_users_path, class: "nav-link" %> </li>
              <% end %>
            <% end %>
          </ul>               
   
          <ul class="nav navbar-nav ms-auto mx-5">
            <% if current_user %>
              <li class="nav-item dropdown">              
                <a href="#" class="dropdown-toggle text-light" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user"></span>                  
                    <%= current_user.display_name %>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to '維護活動分類', admin_categories_path, :class => "dropdown-item text-dark" %></li>
                  <li><%= link_to '修改密碼', edit_registration_path(:user), :class => "dropdown-item text-dark" %></li>
                  <li><%= link_to '登出', destroy_user_session_path, :method => :delete, :class => "dropdown-item text-dark" %></li>                       
                </ul>
              </li>
            <% else %>
              <li><%= link_to '註冊', new_registration_path(:user), :class => "dropdown-item text-dark" %></li>|
              <li><%= link_to '登入', new_session_path(:user), :class => "dropdown-item text-dark" %></li>
            <% end %>

            <!-- 下列寫法是要導向到當前的controller和action,而不是某個指定的controller和action-->
            <li class="nav-item dropdown mx-3 ">
              <a href="#" class="dropdown-toggle text-light" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user"></span>                  
                <%= t( "Locale") %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">     
                <li><%= link_to "中文版", { :controller => controller_name, :action => action_name, :locale => "zh-CN" }, class: "dropdown-item" %></li>
                <li><%= link_to "English", { :controller => controller_name, :action => action_name, :locale => "en" }, :class => "dropdown-item" %></li>
              </ul>
            </li> 
          </ul>
        </div>

      </nav>

      
    </div>    

    <div style="margin-top: 5rem;"></div> <!--把下面的內容往下擠,讓內容不被遮蓋-->   

    <div class="mx-3"> 
      <% if notice %>
        <p class="notice alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

rails_recipes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application" %>

  </head>

  <body>
    <div class="container-fluid">
      <!-- "navbar-expand-lg" 当屏幕尺寸达到 lg（大于等于 992 像素）时，导航栏将橫向扩展为全屏幕。-->
      <!-- <nav class="navbar navbar-default"> bs5中,"navbar-default"已被.navbar-light和.navbar-dark類別取代-->
      <nav class="navbar navbar-expand-md navbar-light bg-light mx-3">  
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">全栈营 Rails Recipes 前台</a>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav">
            <li class="nav-item">        
              <a class="nav-link" href=<%= events_path%> aria-current="page">活動一覽</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup='true' aria-expanded="false">
                Ajax 練習
              </a>                              
                <ul class="dropdown-menu">
                <li><%= link_to "jQuery 練習一", jquery_1_path, :class => "dropdown-item" %></li>
                <li><%= link_to "jQuery 練習二", jquery_2_path, :class => "dropdown-item" %></li>
                <li><%= link_to "jQuery 練習三", jquery_3_path, :class => "dropdown-item" %></li>
                <li><%= link_to "jQuery 練習四", jquery_4_path, :class => "dropdown-item" %></li>
                <li><%= link_to "jQuery 練習五", jquery_5_path, :class => "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Card Tab", card_tab_path, :class => "dropdown-item" %></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          
          <ul class="navbar-nav ms-auto mx-5">
            <% if current_user %>
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-user"></span>   
                  <%= t("hello", :name => current_user.display_name) %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">    
                  <li><%= link_to '管理員面板', admin_events_path, :class => "dropdown-item" %></li>
                  <li><%= link_to '我的個人資料', user_path, :class => "dropdown-item" %></li>
                  <li><%= link_to '修改個人資料', edit_user_path, :class => "dropdown-item" %></li>                          
                  <li><%= link_to '修改密碼', edit_registration_path(:user), :class => "dropdown-item" %></li>
                  <li><%= link_to '登出', destroy_user_session_path, :method => :delete, :class => "dropdown-item" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to '註冊', new_registration_path(:user), :class => "dropdown-item" %></li>|
              <li><%= link_to '登入', new_session_path(:user), :class => "dropdown-item" %></li>
            <% end %>
            
            <!-- 下列寫法是要導向到當前的controller和action,而不是某個指定的controller和action-->
            <li class="nav-item dropdown mx-3 ">
              <a href="#" class="dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user"></span>                  
                <%= t( "Locale") %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">     
                <li><%= link_to "中文版", { :controller => controller_name, :action => action_name, :locale => "zh-CN" }, class: "dropdown-item" %></li>
                <li><%= link_to "English", { :controller => controller_name, :action => action_name, :locale => "en" }, :class => "dropdown-item" %></li>
              </ul>
            </li> 
          </ul>
        </div>

      </nav>
    </div>    

    <div class="mx-3"> 
      <% if notice %>
        <p class="notice alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>