ajax2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :posts do
    member do
      post "like" => "posts#like"
      post "unlike" => "posts#unlike"
      post "toggle_flag" => "posts#toggle_flag"
      post "rate" => "posts#rate"
    end
  end

  get "/jquery-1" => "pages#jquery_1"
  get "/jquery-2" => "pages#jquery_2"
  get "/jquery-3" => "pages#jquery_3"
  get "/jquery-4" => "pages#jquery_4"
  get "/jquery-5" => "pages#jquery_5"
  get "/card-tab" => "pages#card_tab"

  #root "pages#jquery_1"
  root "posts#index"

end

ajax2/app/models/category.rb
class Category < ApplicationRecord
    # ***** 4-7 使用下拉選單(select)分類貼文 *****
    has_many :posts
end

ajax2/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

ajax2/app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :content
    
    belongs_to :user

    has_many :likes, :dependent => :destroy
    has_many :liked_users, :through => :likes, :source => :user


    

    def find_like(user)       
      self.likes.where( :user_id => user.id ).first
    end

    # ***** 4-7 使用下拉選單(select)分類貼文 *****
    belongs_to :category, :optional => true   # 可以不屬於任何category

    # ***** 4-10 jQuery Plugin 整合示範(cont) *****
    has_many :scores, :class_name => "PostScore"

    def find_score(user)
      user && self.scores.where( :user_id => user.id ).first
    end

    def average_score
      self.scores.average(:score)
    end

end

ajax2/app/models/post_score.rb
class PostScore < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

ajax2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts

  has_many :likes, :dependent => :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  def display_name
    self.email.split("@").first
  end

  def is_admin? 
    role == "admin"
  end
end

ajax2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

ajax2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 在執行 create 和 destroy 方法前,先執行指竹的方。
  # 所以這段的用意是,在執行create和destroy之前,先檢查使用者是否登入比驗證是是,
  # 若未通過身份驗證, 則導向登入頁面或顯示錯誤信息。
  before_action :authenticate_user!, :only => [:create, :destroy]

  def index    
    #@posts = Post.order("id DESC").all    # 新貼文放前面
    @posts = Post.order("id DESC").limit(10)

    if params[:max_id]
        @posts = @posts.where( "id < ?", params[:max_id])
    end

    respond_to do |format|
        format.html  # 如果客戶端要求 HTML，則回傳 index.html.erb
        format.js    # 如果客戶端要求 JavaScript，回傳 index.js.erb
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    #@post.save
    
    if @post.save
      render json: { post: render_to_string(partial: 'post', locals: { post: @post }) }
    else
      render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end
  
  end

  def destroy
    @post = current_user.posts.find(params[:id])  # 只能刪除自己的貼文
    @post.destroy

    #redirect_to posts_path
    #render :js => "alert('OK !');"   
    render :json => { :id => @post.id }
  end

  def update
    @post = Post.find(params[:id])
    @post.update!( post_params )

    render :json => { :id => @post.id, :message => "ok"}
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user)  # 如果已經按讚過了，就略過不再新增
      Like.create( :user => current_user, :post => @post)
    end

    #redirect_to posts_path
  end

  def unlike
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    #redirect_to posts_path
    render "like"
  end
    
  # ***** 4-4 使用核選方塊(checkbox)做開關 *****
  def toggle_flag
    @post = Post.find(params[:id])

    if @post.flag_at
      @post.flag_at = nil
    else
      @post.flag_at = Time.now
    end

    @post.save!

    render :json => { :message => "ok", :flag_at => @post.flag_at, :id => @post.id }
  end

  # ***** 4-10 jQuery Plugin 整合示範(cont) *****
  def rate
    @post = Post.find(params[:id])

    existing_score = @post.find_score(current_user)
    if existing_score
      existing_score.update( :score => params[:score] )
    else
      @post.scores.create( :score => params[:score], :user => current_user )
    end

    render :json => { :average_score => @post.average_score }
  end

  protected

  def post_params
    params.require(:post).permit(:content, :flag_at, :category_id)
  end

end

ajax2/app/helpers/pages_helper.rb
module PagesHelper
end

ajax2/app/helpers/posts_helper.rb
module PostsHelper
end

ajax2/app/views/pages/card_tab.html.erb
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" data-bs-toggle="tab" href="#tab1" aria-current="true">Link1</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" href="#tab2">Link2</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="tab" href="#tab3">Link3</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" data-bs-toggle="tab" href="#tab4">Disabled</a>
      </li>
    </ul>
  </div>

  <div class="card-body">
    <div class="tab-content">
        <div id="tab1" class="tab-pane fade show active text-start">
            <h5 class="card-title">AAA Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
            
        <div id="tab2" class="tab-pane fade">    
            <h5 class="card-title">BBB BBBBBBB</h5>
            <p class="card-text">bbbbb With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">bbb Go somewhere</a>
        </div>

        <div id="tab3" class="tab-pane fade text-end">    
            <h5 class="card-title">CCC CCCCCCCC</h5>
            <p class="card-text">ccccc With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">bbb Go somewhere</a>
        </div>

        <div id="tab4" class="tab-pane fade">
            <h5 class="card-title">DDDDDDDD</h5>
            <p class="card-text">dddd With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">ddd Go somewhere</a>
        </div>
    </div>
  </div>
</div>

ajax2/app/views/pages/jquery_1.html.erb
<script>
  $(function(){
    $("#my-click").click(function(){
      $("#foo").html("<h1>Hello, world !</h1>");
    })
  })
</script>

<p>
  <a id="my-click">Click Me</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

ajax2/app/views/pages/jquery_2.html.erb
<p>
  <a id="my-open-click">Open</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-hide-click">Hide</a>
  <p>bar</p>
</div>

<script>
  $("#foo").hide();

  $("#my-open-click").click(function(){
    $("#foo").show();
  })

  $("#my-hide-click").click(function(){
    $("#foo").hide();
  })
</script>

ajax2/app/views/pages/jquery_3.html.erb
<p>
  <a id="my-toggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#foo").hide();   // 先馬上藏起來

  $("#my-toggle-click").hover(function(){
    $("#foo").toggle();   // 移過去會有開關的效果, 在 jQuery 3.0 版本之后，toggle() 方法已经被移除了
  })

</script>

ajax2/app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border:3px solid red;">
  <p>bar</p>
</div>

<div class="zoo"><p>a</p></div>
<div class="zoo"><p>b</p></div>
<div class="zoo"><p>c</p></div>

<script>
  $("#my-replace-click").click(function(){
    $("#foo").replaceWith('<div id="foo" style="border:3px solid green"><p><h1>FOO</h1></p></div>');
  })

  $("#my-remove-click").click(function(){
    $("#foo").remove();
  })

  $("#my-remove-all-click").click(function(){
    $(".zoo").remove();
  })
</script>

ajax2/app/views/pages/jquery_5.html.erb
<style>
  .error {
    color: red;
  }
  .success {
    color: green;
  }
</style>

<p>
  <a id="my-add-class-click">Add Class</a>

  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<script>
  $("#my-add-class-click").click(function(){
    $("#foo").removeClass('error');
    $("#foo").addClass('success');
  })

  $("#my-remove-class-click").click(function(){
    $("#foo").removeClass('success');
    $("#foo").addClass('error');
  })
</script>

ajax2/app/views/posts/_like.html.erb
<% if post.liked_users.any? %>
    <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 點了贊
<% end %>

<% if current_user # 有登入才可以按讚 %>
    <% if post.find_like(current_user) %>
      <%= link_to "取消讚", unlike_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
    <% else %>
      <%= link_to "讚", like_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
    <% end %>
<% end %>

ajax2/app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="card my-3">
  <div class="card-header">
    <%= post.user.display_name %>
  </div>

  <div class="card-body">  
    <span id="post-thumbsup-<%= post.id %>" class="badge bg-success"><%= post.likes.count %> 👍</span>    
    <span class="average-score"><%= post.average_score %></span>
    <div class="raty" data-score="<%= post.find_score(current_user).try(:score) || 0 %>" data-score-url="<%= rate_post_path(post) %>"></div>
    <%= post.content %>

    <div class="text-end">  
      <span id="post-like-<%= post.id %>">
        <%= render :partial => "like", :locals => { :post => post } %>
      </span>

      <% if current_user && post.user == current_user %>    
         <!--這裏':method => :delete' 刪除了,因為在後面的jquery裏的ajax參數裏可以找到 method: delete-->        
        <%= link_to "delete", post_path(post), :class => "delete-post btn btn-danger" %>                  
      <% end %>
    </div>

  </div>  

  <div class="card-footer">
    <% if current_user && current_user.is_admin? %>
      <%= select_tag "category_id[#{post.id}]", 
                options_for_select(Category.all.map{ |x| [x.name, x.id]}, post.category_id), 
                :data => { :url => post_path(post) }, 
                :prompt => "請選擇分類", 
                :class => "select_category" %>
                
      <label>
        <%= check_box_tag "mark_flag[#{post.id}]", 1, post.flag_at.present?,
            :data => { :url => toggle_flag_post_path(post) }, :class => "toggle-flag" %> 標記為垃圾
        <span id="post-flag-<%= post.id %>"><%= post.flag_at %></span>
      </label>
    <% end %>
  </div>

</div>

ajax2/app/views/posts/create.js.erb
<% if @post.valid? %>
  $("#post-list").prepend("<%= j render :partial => "post", :locals => { :post => @post } %>");
  $("#post_content").val("");
<% else %>
  alert("貼文失敗 !");
<% end %>

ajax2/app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

ajax2/app/views/posts/index.html.erb
<%= form_for Post.new, :url => posts_path do |f| %>
  <!--
    form-group 用於包裝表單元素, 當表單元素需要與其標籤(label)一起顯示時，
    可以使用 form-group 類將它們包裝在一起, 可以幫助調整表單元素的垂直間距，使其外觀更加美觀。
    form-control 它將添加樣式，使其填滿其父元素，並在瀏覽器中呈現一致的外觀。
    常用於 input、textarea、select 等表單元素，以提高表單的使用體驗。
  -->
  <div class="form-group my-3">
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group my-3">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

<div id="post-list">
  <% @posts.each do |post| %>
    <%= render :partial => "post", :locals => { :post => post }%>
  <% end %>
</div>


<script>

  // ***** 4-2 把刪除改成自行綁事件 *****  
  //$(".delete-post").click(function(evt){   // 瀏覽器並不會為新增的元素自動綁定事件上去。所以後來 Ajax 新增上去的貼文是沒有事件的。 
  $("#post-list").on("click", ".delete-post", function(evt){
    // `evt`是瀏覽器的事件物件，它代表著當前被觸發的事件。
    // evt.preventDefault(); 會終止這個元素的預設行為：
    // 超連結 a 的預設行為是跳到下一頁，如果沒有這行的話，送出 ajax 後會跳去 show page   
    evt.preventDefault();
    // this 是個特別的變數，代表觸發事件的元素。使用 attr 讀取元素的屬性，這裡要拿到超連結的網址
    var url = $(this).attr("href"); 
    var that = this;  //既然已經知道是哪一個元素被點擊了,就把該元素保留起來,到時拿出來用,就不必用id定位了。
    
    $.ajax({
       // 從 url 和 method 可得知要連接到控制器的 destroy 而不是 show, 
       // 不過要先有 evt.preventDefault(); 不然,早就跳去show了。
      url: url,
      method: 'delete',   // method: 'delete' 是把參數加在url後面,以get的方式傳給服務,所以不需要 data 參數
      //dataType: 'script' // 要求伺服器回傳 javascript
      dataType: 'json', // 要求伺服器回傳 json
      success: function(data){   // data 就是伺服器回傳的 JSON 資料            
        $("#post-" + data["id"]).remove();
        //$(that).closest(".card").remove();         
      }
    })
  })

  // ***** ajax 新增事件 *****
  $(document).on('submit', 'form#new_post', function(e){
    e.preventDefault();
    var form = $(this);
    var url = form.attr("action");
    var method = form.attr("method");    // method: "post", 是通過form 把數據傳給服務器,所以需要下列的data參。
    // 把表單的數據轉換成可提交的格式，
    //表單控制項的名稱和值會被轉換為以下格式：name1=value1&name2=value2&name3=value3...。
    //這樣的格式可以被作為請求的參數提交到後端，後端可以通過解析這個參數字符串來獲取表單數據。
    var data = form.serialize(); 
    
    $.ajax({
      url: url,
      method: method,
      data: data,       // 要傳給伺服器的資料,要配合上述的 form.serialize()
      dataType: 'json',
      success: function(response){
        if (response.post) {          
          $("#post-list").prepend(response.post);          
          $("#post_content").val("");
        } else {
          alert("貼文失敗！");
        }    
      },
      error: function(jqXHR, textStatus, errorThrown) {    
        var errors = $.parseJSON(jqXHR.responseText).errors;    
        alert(errors.join(", "));  
      }

    });
  })
 

  // ***** 4-3 貼文無限捲軸 *****  
  var current_post_id = <%= @posts.last.id %>;    // 記下目前畫面最小的貼文 ID

  // 當捲軸動的時候，會觸發這個事件
  $(window).scroll(function(){        
    // 當捲到最下面的時候
    //if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {  
    if($(window).scrollTop() + $(window).height() + 2 >= $(document).height()) {  // 不是很敏感,經常判斷不到觸底事件發。加2的作用是要確保 ">=" 一定要成立      
      var url = "/posts?max_id=" + current_post_id;
      if(url){
        $.ajax({
            method: "GET",
            url: url,
            dataType: "script"
        })
      } else {
        console.log("data ended");
      }
    }
  })

  // ***** 4-4 使用核選方塊(checkbox)做開關 *****
  //$(".toggle-flag").on("change",function(){   
  $("#post-list").on('change', ".toggle-flag", function(){   // change 是事件名稱 ，表示輸入框有變動的話，就會觸發。
    var url = $(this).data("url");
    var that = this

    $.ajax({
      url: url,
      method: "POST",
      dataType: "json",
      success: function(data){
        if ( data["flag_at"] ) {
          //$("#post-flag-" + data["id"]).html(data["flag_at"]);
          $(that).closest("label").find("span").html(data["flag_at"]);  // ***** 4-6 使用 jQuery Traversing 走訪元素 *****
        } else {
          //$("#post-flag-" + data["id"]).html("");
          $(that).closest("label").find("span").html("");    // ***** 4-6 使用 jQuery Traversing 走訪元素 *****
        }
      }
    });
  });

  // ***** 4-7 使用下拉選單(select)分類貼文 *****
  $("#post-list").on('change', ".select_category", function(){
     var url = $(this).data("url");

    $.ajax({
      url: url,
      method: "PATCH",
      dataType: "json",
      data: {    // data 是要傳遞給服務器的參數
        post: {
          category_id: $(this).val()
        }
      }
    });
  });
  
  // ***** 4-9 jQuery Plugin 整合示範 *****
  //$(".raty").raty( { path: '/images/' } );

  // ***** 4-10 jQuery Plugin 整合示範 *****
  $(".raty").raty({ 
      path: '/images/',   // 指定圖片的路徑，該路徑用於從外掛程式中加載星星的圖像。      
      score: function() { return $(this).data('score'); },   // score 選項是一個回調函數，從元素的 data-score 屬性中獲取每個元素的分數。
      click: function(score) {
        var that = this;
        $.ajax({
          url: $(this).data("score-url"),
          method: "POST",
          data: { score: score },
          dataType: "json",
          success: function(data){
            $(that).closest(".card-body").find(".average-score").html( data["average_score"] );
          }
        })
      }
  });

</script>

ajax2/app/views/posts/index.js.erb
<% @posts.each do |post| %>
  $("#post-list").append("<hr>")
  $("#post-list").append("<%=j render :partial => "post", :locals => { :post => post } %>");
<% end %>

<% if @posts.any? %>
  var current_post_id = <%= @posts.last.id %>;
<% end %>

ajax2/app/views/posts/like.js.erb
str = "<%=j render :partial => "like", :locals => { :post => @post } %>";
$("#post-like-<%= @post.id %>").html(str);

$("#post-thumbsup-<%= @post.id %>").html("<%= @post.likes.count %>" + " 👍")