rails_recipes/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :events do
    # ***** 16-2 建立報名、16-3 多步驟表單(wizards) *****
    resources :registrations do
      member do
        get "steps/1" => "registrations#step1", :as => :step1
        patch "steps/1/update" => "registrations#step1_update", :as => :update_step1        
        get "steps/2" => "registrations#step2", :as => :step2
        patch "steps/2/update" => "registrations#step2_update", :as => :update_step2       
        get "steps/3" => "registrations#step3", :as => :step3
        patch "steps/3/update" => "registrations#step3_update", :as => :update_step3
      end
    end
  end
  
  resource :user  # 這個單數的用意是指唯一自己，登入作戶也不能修改其他人的資。

  namespace :admin do     #定義了一個命名空間,並在其中定義了其他資源。    
    resources :events do
      resources :registrations, :controller => "event_registrations"  
      resources :tickets, :controller => :event_tickets
      collection do
        post :bulk_update
      end 
      
      member do
        post :reorder
      end

    end

    resources :categories
    resources :users do
      resource :profile, :controller => :user_profiles
    end
    
    root "events#index"   #访问 "/admin" 路径时，会执行 "events#index" 动作。
  end

  
  get "/jquery-1" => "pages#jquery_1"
  get "/jquery-2" => "pages#jquery_2"
  get "/jquery-3" => "pages#jquery_3"
  get "/jquery-4" => "pages#jquery_4"
  get "/jquery-5" => "pages#jquery_5"
  get "/card-tab" => "pages#card_tab"
  
  root "events#index"

end

rails_recipes/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  has_many :memberships
  has_many :groups, :through => :memberships

  has_one :profile
  
  accepts_nested_attributes_for :profile
  
  # ***** 16-1 需求和 Model 設計 *****
  has_many :registrations

  ROLES = ["admin", "editor"]

  def display_name
    self.email.split("@").first
  end

  def is_admin?
    self.role == "admin"
  end

  def is_editor?
    ["admin", "editor"].include?(self.role)  # 如果是 admin 的話，當然也有 editor 的權限
  end

end

rails_recipes/app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin!
  
  def index
    #@users = User.all
    @users = User.includes(:groups).all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  protected

  def user_params   
    #params.require(:user).permit(:email, :group_ids => [])
    params.require(:user).permit(:email, :role, :group_ids => [])
  end
end

rails_recipes/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def edit
    @user = current_user

    # 跟剛才後台情況一樣，如果沒有 @user.profile，要先新建一個。
    # unless @user.profile 等同於 if !@user.profile 或 if @user.profile.nil?
    @user.create_profile unless @user.profile
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  protected

  def find_user
    @user = current_user
    @user.create_profile unless @user.profile
  end
  
  def user_params
    #params.require(:user).permit(:time_zone)
    params.require(:user).permit(
      :time_zone, 
      :profile_attributes => [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty] 
    )
  end   
end

rails_recipes/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rails_recipes/app/helpers/users_helper.rb
module UsersHelper
end

rails_recipes/app/views/admin/users/edit.html.erb
<h1>t("admin.edit_user')</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user, :url => admin_user_path(@user), :method => :patch do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.select :role, User::ROLES.map{ |x| [t(x, :scope => "user.role"), x] }, { :include_blank => true }, :class => "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :group_ids %>
    <%= 
      #f.collection_check_boxes(:group_ids, Group.all, :id, :name) 
    %>
    <%= f.select :group_ids, Group.all.map{ |g| [g.name, g.id] }, {}, :multiple => true, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit t("update"), :class => "btn btn-primary" %> 
    <%= link_to t("cancel"), admin_users_path, :class => "btn btn-default" %>
  </div>

<% end %>


<script>
  $("#user_group_ids").select2()
</script>

rails_recipes/app/views/admin/users/index.html.erb
<div style="margin-top: 4rem;"></div> <!--把下面的內容往下擠,讓內容不被遮蓋-->
<h1>admin_users</h1>

<table class="table">
  <tr>
    <th>id</th>
    <th>email</th>
    <th>Groups</th>
    <th>actions</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email%></td>
    <td>
      <% user.groups.each do |g| %>
        <%= g.name%><br>
      <% end %>
    </td>
    <td><%= link_to t("edit"), edit_admin_user_path(user), :class => "btn btn-default" %></td>
    <td><%= link_to t("edit_profile"), edit_admin_user_profile_path(user), :class => "btn btn-primary" %></td>
  </tr>
  <% end %>
</table>